##################################################
# Menus (English)
##################################################

main:
  # Top row (4)

  - name: Calculator
    pre: tf-ion-calculator
    url: https://nftreasure.gitlab.io/calculator/
    weight: 1

  - name: Marketplace
    pre: tf-basket
    url: https://nftreasure.gitlab.io/community-marketplace/
    weight: 2

  - name: Daycare
    pre: "U+1F37C"
    url: https://nftreasure.gitlab.io/daycare/
    weight: 3

  - name: Diamond Hands
    pre: tf-ion-android-hand
    url: https://www.smarterswap.xyz/search
    weight: 4

  # Bottom row (3)

  - name: Strategies
    pre: tf-ion-android-bulb
    url: strategies/overview
    weight: 5

  - name: Ron Jay
    pre: tf-profile-male
    url: ron-jay/who
    weight: 6

    # About     7
    # Resume    8

  - name: Contact
    pre: tf-envelope2
    url: contact/
    weight: 9
