##################################################
# Menus (English)
##################################################

main:

  # Top row (4)

  - name: Calculator
    pre: tf-ion-calculator
    url: https://nftreasure.gitlab.io/calculator/
    weight: 1

  - name: Community Marketplace
    pre: tf-basket
    url: https://nftreasure.gitlab.io/community-marketplace/
    weight: 2

  - name: Daycare
    pre: tf-dribbble
    url: https://nftreasure.gitlab.io/daycare/
    weight: 3

  - name: Diamond Hands Allocation
    pre: tf-ion-star
    url: https://www.smarterswap.xyz/search
    weight: 4

  # Bottom row (3)

  - name: Strategies
    pre: tf-genius
    url: strategies/
    weight: 5

  - name: Ron Jay
    pre: tf-profile-male
    url: ron-jay/welcome
    weight: 6

    # Welcome   6
    # About     7
    # Resume    8
    # Chat      9

  - name: Contact
    pre: tf-envelope2
    url: contact/
    weight: 10
