##################################################
# Menus (English)
##################################################

# Top row (4)
main:
  - name: Calculator
    pre: tf-ion-calculator
    url: https://nftreasure.gitlab.io/calculator/
    weight: 1

  - name: Marketplace
    pre: tf-basket
    url: https://nftreasure.gitlab.io/community-marketplace/
    weight: 2

  - name: Daycare
    pre: tf-ion-home
    url: https://nftreasure.gitlab.io/daycare-v4/
    weight: 3

  - name: Diamond Hands
    pre: tf-ion-android-hand
    url: https://www.smarterswap.xyz/search
    weight: 4

  # Middle row (3)
  - name: Strategies
    pre: tf-ion-android-bulb
    url: strategies/overview
    weight: 5

  - name: Ron Jay
    pre: tf-profile-male
    url: ron-jay/who
    weight: 6

    # About     7
    # Resume    8

  #- name: Keys
  #  pre: tf-key
  #  url: keys/
  #  weight: 9

  # Bottom row (2)
  - name: Contact
    pre: tf-envelope1
    url: contact/
    weight: 10
