##################################################
# Menus (English)
##################################################

main:
  # Top row (4)
  - name: Calculator
    pre: tf-ion-calculator
    url: https://nftreasure.gitlab.io/calculator/
    weight: 1

  - name: Marketplace
    pre: tf-basket
    url: https://nftreasure.gitlab.io/community-marketplace/
    weight: 2

  - name: Daycare
    pre: tf-ion-home
    url: https://nftreasure.gitlab.io/daycare-v5/
    weight: 3

  - name: Keys
    pre: tf-key
    url: /keys
    weight: 4

  # Bottom row (3)
  - name: Strategies
    pre: tf-ion-android-bulb
    url: strategies/overview
    weight: 5

  - name: Ron Jay
    pre: tf-profile-male
    url: ron-jay/who
    weight: 6

  - name: Contact
    pre: tf-envelope1
    url: contact/
    weight: 7
