# DON'T REMOVE THIS FILE.
# This file is for render site varibles and plugins
#
# The actual configuration files are stored in the `config/_default/` folder.

######################### Site variables ##############################

# customize your color and font from here.
#[params.variables]

###################### Plugins #############################

# CSS Plugins
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Libre+Baskerville:400,400i|Open+Sans:400,600,700,800"

[[params.plugins.css]]
link = "css/bootstrap.min.css"

[[params.plugins.css]]
link = "css/themefisher-fonts.min.css"

[[params.plugins.css]]
link = "css/owl.carousel.min.css"

# JS Plugins
[[params.plugins.js]]
link = "js/jquery-2.2.4.min.js"

[[params.plugins.js]]
link = "js/bootstrap.min.js"

[[params.plugins.js]]
link = "js/isotope.pkgd.min.js"

[[params.plugins.js]]
link = "js/jquery.nicescroll.min.js"

[[params.plugins.js]]
link = "js/owl.carousel.min.js"

[[params.plugins.js]]
link = "js/jquery.easing.min.js"

[[params.plugins.js]]
link = "plugins/youtube-lite.js"

[[params.plugins.js]]
link = "plugins/lazy-loader.js"
