##################################################
# Params
##################################################

chatbot:
  enabled: true

  # Test
  #url: "http://localhost:8787/api"

  # OpenAI
  url: "http://localhost:8787/api-openai"

  # Mistral AI
  #url: "http://localhost:8787/api-mistral"
