---
##################################################
# Name: nix-flake-update.yaml
# Description:
#   A Workflow that updates Nix flake inputs.
##################################################

name: Nix Flake update

on:
  schedule:
    - cron: "0 0 * * 0"

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  statuses: read

env:
  NIXPKGS_ALLOW_UNFREE: 1

jobs:
  nix:
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v4

      - id: install_nix
        name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v20

      - id: cachix
        name: "Enable Cachix ❄️"
        uses: cachix/cachix-action@v12
        with:
          name: salt-labs
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - id: update_nix_flake
        name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v17
        with:
          sign-commits: false
          gpg-fingerprint: ${{ secrets.GPG_FINGERPRINT }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          git-author-email: "github-actions@users.noreply.github.com"
          git-author-name: "Nix Flake Bot"
          git-committer-email: "github-actions@users.noreply.github.com"
          git-committer-name: "Nix Flake Bot"

      - id: print_pr_number
        name: Pull request number
        run: |
          echo PR number: ${{ steps.update_nix_flake.outputs.pull-request-number }}
