---
name: Ship it

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - review_requested
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - review_requested
    paths:
      - devenv.lock

defaults:
  run:
    shell: bash

permissions:
  contents: write
  pull-requests: write
  packages: read

jobs:
  check:
    name: Check PR

    runs-on: ubuntu-latest

    if: |
      (github.event_name == 'pull_request_target' &&
       github.event.pull_request.user.login == 'dependabot[bot]') ||
      (github.event_name == 'pull_request' &&
       github.event.pull_request.user.login == 'github-actions[bot]' &&
       contains(github.event.pull_request.title, 'bump devenv.lock') &&
       github.event.pull_request.head.repo.full_name == github.repository)

    steps:
      - id: dependabot_metadata
        name: Dependabot metadata
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        uses: dependabot/fetch-metadata@v2.2.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          skip-commit-verification: false

      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@v4

      - id: pr_approve
        name: Approve pull request
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.SHIPIT_TOKEN }}
        run: |
          gh pr checkout "$PR_URL"
          if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ];
          then
            gh pr review --approve "$PR_URL"
          else
            echo "PR already approved.";
          fi

      - id: pr_merge
        name: Merge pull request
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.SHIPIT_TOKEN }}
        run: |
          gh pr merge --auto --merge "$PR_URL"
