---
name: Devenv update

on:
  schedule:
    - cron: "0 0 * * 0"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  pull-requests: write
  statuses: read

env:
  # GitHub
  PROJECT: ${{ github.repository }}
  BRANCH_NAME_CURRENT: ${{ github.head_ref || github.ref_name }}
  BRANCH_NAME_DEFAULT: ${{ github.event.repository.default_branch }}

  # Nix
  NIXPKGS_ALLOW_UNFREE: 1

defaults:
  run:
    shell: bash

jobs:
  nix:
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v4

      - id: install_nix
        name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          enable_kvm: true

      - id: cachix
        name: "Enable Cachix ❄️"
        uses: cachix/cachix-action@v15
        if: vars.CACHIX_CACHE_NAME != ''
        with:
          name: ${{ vars.CACHIX_CACHE_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          useDaemon: true
          skipPush: false

      - id: cache
        name: Magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - id: devenv_install
        name: Devenv install
        run: |
          nix profile install nixpkgs#devenv

      - id: devenv_update
        name: Devenv update
        run: |
          devenv update

      - id: create_pull_request
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "bump devenv.lock"
          title: "bump devenv.lock"
          body: "This PR bumps the flake input dependencies"
          branch: "bump-devenv-lock"
          base: ${{ env.BRANCH_NAME_DEFAULT }}
          labels: "dependencies"
          assignees: "MAHDTech"
          reviewers: "MAHDTech"
          draft: false
          signoff: true
          delete-branch: true
          sign-commits: true
